### ISSUE TITLE
Not on Clojars

### ISSUE THREAD

**Issue by TotNotTac** [lambdaisland/trikl#3]
This looks like a good library, too bad it's dead :/

**Comment by plexus** [comment]
https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9

**Comment by plexus** [comment]
I added a section in the README to clarify the status of this project.

Please respect open source creators and maintainers, and don't post highly entitled messages like this one.

**Comment by TotNotTac** [comment]
My apologies, it was not my intention to come over as entitled in any way. I genuinely would like to use this library, however I'm relatively new to Clojure and I'm not sure how to use a library locally. This is Github and not the Youtube comment section, so I'll refrain from making such comments from now on. Once again, I meant no disrespect, I'm a big fan of your AOC in Clojure videos.

**Comment by plexus** [comment]
Alright then, no offence taken. Trikl is a project I get back to every so often, it's very much my personal baby. I have a vision for what I want it to be, and I've explored a lot, but it's not there yet, and the way things are taking off with Gaiwan I likely won't have time for it for the foreseeable future. It's the kind of project I get to spend two days on on the second week of a long holiday.

The examples in the readme might still mostly work, I'm not sure, I might have moved some stuff around and broken some things in the process... I'm basically onto the third rewrite, trying to incorporate the learnings from the first two versions.
